### ISSUE TITLE
Ludusavi can't make backup to Final Fantasy IX - Steam version

### ISSUE THREAD

**Issue by OmegaOmega** [mtkennerly/ludusavi-playnite#27] opened 2021-11-15 22:37 UTC
So. I can't make the backup file for FF IX. I receive the following error:
"Backed up saves for FINAL FANTASY IX 0 b of 3.17 MiB, but some saves failed"

Ludusavi creates a folder with a huge name correctly, but can't backup the savefile itself
 (C:\Users\[USER]\Cloud\Saves\ludusavi\Final Fantasy IX\drive-C\Users\[USER]\AppData\LocalLow\SquareEnix\FINAL FANTASY IX\Steam\EncryptedSavedData

**Comment by mtkennerly** [comment] 2022-01-15 02:53
Hmm, it's hard to say why this would happen. It looks like the path is well under the Windows 260 character limit, and I don't know why there would be a permissions issue with just the one file. I don't own the game, but if I get it at some point, I can try this on my system to see if I can reproduce it.

**Comment by mtkennerly** [comment] 2022-05-13 23:31
I was finally able to test this just now, but it's working fine on my end, both through Ludusavi itself and through the Playnite extension. I see that your backup path includes `C:\Users[USER]\Cloud` - perhaps the issue is related to your cloud storage. Some questions for you:

* What cloud provider do you use?
* Could you try using a regular local folder and see if it still happens?

I'm going to close this for now since it seems like a system- or cloud-specific issue, but I'm happy to reopen it if we can identify something defective/deficient in Ludusavi itself.

**Closed by mtkennerly** 2022-05-13 23:31 UTC
Labels: bug
